import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Skeleton } from '@/components/ui/skeleton';
import { Textarea } from '@/components/ui/textarea';
import {
  NativeAvatar,
  NativeBadge,
  NativeCard,
  NativeCardContent,
  NativeCardHeader,
  NativeCardTitle,
  NativeCheckbox,
  NativeDescriptionList,
  NativeDialog,
  NativeDialogContent,
  NativeDialogDescription,
  NativeDialogFooter,
  NativeDialogHeader,
  NativeDialogTitle,
  NativeDialogTrigger,
  NativeEmptyState,
  NativeGrid,
  NativeNotice,
  NativePagination,
  NativeProgress,
  NativeRadioGroup,
  NativeSelect,
  NativeSeparator,
  NativeSplit,
  NativeStack,
  NativeStat,
  NativeSwitch,
  NativeTable,
  NativeTableBody,
  NativeTableCell,
  NativeTableHead,
  NativeTableHeader,
  NativeTableRow,
  NativeTabs,
  NativeTabsContent,
  NativeTabsList,
  NativeTabsTrigger,
  NativeTooltip,
  NativeTooltipContent,
  NativeTooltipProvider,
  NativeTooltipTrigger,
} from './NativeUIKit';

export const nativeUIKit = {
  Button,
  Card: NativeCard,
  CardHeader: NativeCardHeader,
  CardTitle: NativeCardTitle,
  CardContent: NativeCardContent,
  Badge: NativeBadge,
  Notice: NativeNotice,
  Skeleton,
  Separator: NativeSeparator,
  Progress: NativeProgress,
  Table: NativeTable,
  TableHeader: NativeTableHeader,
  TableBody: NativeTableBody,
  TableRow: NativeTableRow,
  TableHead: NativeTableHead,
  TableCell: NativeTableCell,
  Tabs: NativeTabs,
  TabsList: NativeTabsList,
  TabsTrigger: NativeTabsTrigger,
  TabsContent: NativeTabsContent,
  Input,
  Textarea,
  EmptyState: NativeEmptyState,
  Select: NativeSelect,
  Checkbox: NativeCheckbox,
  RadioGroup: NativeRadioGroup,
  Switch: NativeSwitch,
  Dialog: NativeDialog,
  DialogContent: NativeDialogContent,
  DialogHeader: NativeDialogHeader,
  DialogTitle: NativeDialogTitle,
  DialogDescription: NativeDialogDescription,
  DialogFooter: NativeDialogFooter,
  DialogTrigger: NativeDialogTrigger,
  Tooltip: NativeTooltip,
  TooltipTrigger: NativeTooltipTrigger,
  TooltipContent: NativeTooltipContent,
  TooltipProvider: NativeTooltipProvider,
  Stat: NativeStat,
  DescriptionList: NativeDescriptionList,
  Avatar: NativeAvatar,
  Pagination: NativePagination,
  Stack: NativeStack,
  Grid: NativeGrid,
  Split: NativeSplit,
};
