#!/usr/bin/env node
import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const labRoot = resolve(fileURLToPath(new URL("..", import.meta.url)));
const sourcePath = join(labRoot, "gateway", "nginx.conf");
const outputRoot = join(labRoot, ".runtime", "generated", "gateway");
const outputPath = join(outputRoot, "nginx.conf");
const publicGatePath = process.env.PUBLIC_GATE_PATH?.trim();
if (!publicGatePath || !/^interop-[a-f0-9]{24}$/.test(publicGatePath)) {
  throw new Error(
    "PUBLIC_GATE_PATH must be generated by scripts/init-env.mjs before preparing the gateway",
  );
}
const template = await readFile(sourcePath, "utf8");
if (!template.includes("__PUBLIC_GATE_PATH__")) {
  throw new Error("Gateway source is missing its public-path placeholder");
}
const document = template.replaceAll("__PUBLIC_GATE_PATH__", publicGatePath);
if (document.includes("__PUBLIC_GATE_PATH__")) {
  throw new Error("Gateway public-path substitution was incomplete");
}
await mkdir(outputRoot, { recursive: true });
await writeFile(outputPath, document, { mode: 0o644 });
await chmod(outputPath, 0o644);
console.log(`Prepared random-path gateway config at ${outputPath}`);
